homematicip/__init__.py
Since I'm on macOS this bothered me a bit. ;)
=> Platform and locale is determined automatically.

homematicip/device.py
added comments for device classes
tested set_display for HMIP-WTH (HMIP-WTH and HMIP-WTH-2 are identical, only the firmware version differs)
added and tested set_display for HMIP-STHD
=> added set_display for HMIP-STHD

homematicip/group.py, homematicip_cli.py
* `--list-group-ids`
* `--group`
* `--activate-absence`
* `--deactivate-absence`
* `--list-profiles`
* `--activate-profile`
=> Added cli commands

homematicip/home.py
this is probably also needed for other API calls.
=> Uppercase T in endTime to avoid invalid request

dump_devicevalues.py
Hi,
I created a bugfix für #30 
Signed-off-by: David <david@hoffmann-projects.de>
=> BugFix #30

homematicip_cli.py
Signed-off-by: David <david@hoffmann-projects.de>
=> Bugfix for issue #32

generate_auth_token.py, homematicip/HomeMaticIPObject.py, homematicip/__init__.py, homematicip/auth.py, homematicip/connection.py, homematicip/device.py, homematicip/group.py, homematicip/home.py, homematicip/securityEvent.py, homematicip_cli.py
Moving urls and tokens away from global variables allows for controlling multiple HMIP access points inside one python process and eases addition of asyncio functionality.
=> Moving urls and tokens away from global variables to a connection class.

README.md, homematicip/HomeMaticIPObject.py, homematicip/device.py, homematicip/group.py, homematicip/home.py, homematicip/securityEvent.py, homematicip_cli.py
- super() method call change.
- removed all unicode definitions from strings ("u")
- replaced all __unicode__ methods with __str__ methods.
Likely this PR will break python 2.7 compatibilty.
=> Moving to Python3

homematicip/class_maps.py, homematicip/home.py
- Moved type maps to a separate file
- Setting `type maps` as class attributes. Allows for later overriding.
- Some general cleanups
=> re-arranging type_maps.

homematicip/async/class_maps.py, homematicip/async/connection.py, homematicip/async/device.py, homematicip/async/group.py, homematicip/async/home.py, homematicip/base/base_connection.py, homematicip/home.py, homematicip_cli_async.py, tests/fake_hmip_server.py, tests/json_data/plugable_switch_measuring.py, tests/json_data/wall_mount_remote_control.py, tests/test_base_connection.py, tests/test_connection_async.py
Mainly changes on the async part like adding device, more tests etc.
Some minor changes to your components.
=> Various changes

homematicip/HomeMaticIPObject.py, homematicip/base/base_connection.py, homematicip/home.py, setup.py, tests/test_home.py, tests/test_plugable_switch_measuring_async.py
Adding update event handler to individual devices to enable direct targeting of specific device updates.
+ Some test
+ Minor changes
+ Bumping version to prepare for future 0.8 release.
=> Adding update event to individual devices

homematicip/base/helpers.py, homematicip/device.py, homematicip/home.py
Code enhancements leading to better error avoidance and maintainability.
=> Several enhancements

dump_devicevalues.py
I added the encoding lag to the dump_devicevalues.py to ensure that the content of the files is utf-8 encoded
=> Dump script dumps in iso encoding

homematicip/home.py, homematicip_cli_async.py
=> Send more info when firing on_update event.

homematicip/async/connection.py, homematicip/async/home.py, homematicip/base/base_connection.py, homematicip_cli_async.py, tests/fake_hmip_server.py, tests/test_connection_async.py
Original was too complex and at times missed a lost connection assuming it was still connected.
Should be fixed now.
=> Rewriting of async websocket connection

homematicip/async/home.py
changed syntax according to the latest asyncio syntax.
=> changed syntax to `async def`

homematicip/async/home.py
Hi, I just implemented a few missing async home functions. 
Ciao Mattias
=> Implement home async functions

homematicip/async/home.py
Sorry but async version of get_security_journal was not working, this is the fix for it.
=> Fix async get_security_journal function

.circleci/config.yml, homematicip/aio/auth.py, requirements.txt, setup.py, tests/aio_tests/test_async_auth.py, tests/conftest.py, tests/fake_cloud_server.py
I made a start to fix aio testing.
For this to work I needed to make some other changes too. Otherwise tests just wouldn't run on my side. They should now be able to run anywhere.
=> fixing aio tests

homematicip.pyproj, homematicip/aio/connection.py, tests/aio_tests/test_connection.py
Improve websocket connection handling and include testing.
=> async websocket connection improvement and testing

homematicip/aio/connection.py, tests/aio_tests/test_connection.py
=> fix async on_message call

homematicip/aio/group.py, homematicip/base/enums.py, homematicip/group.py
Add setControlMode to switch between AUTOMATIC AND MANUAL mode.
=> Add setControlMode function to HeatingGroup

homematicip/device.py
i think this extra logging is not necessary. Function works as expected with my HmIP-BSL.
=> Removed  BSL method logging

hmip_cli.py, homematicip/aio/home.py, homematicip/base/helpers.py, homematicip/home.py, tests/test_hmip_cli.py
Hi,
i'd like to create a service in HA to allow a configuration dump without further setup.
Therefor i needed to do some refactorings to reuse your existing code.
OK?
BR
=> Refactoring of dump configuration

homematicip_demo/__init__.py
Hope this adds the demo package to pypi package.
BR
=> Fix Demo package

MANIFEST.in
I missed the json files for the demo package.
Sorry.
=> Add demo json to manifest for packaging

homematicip/aio/class_maps.py, homematicip/aio/device.py, homematicip/class_maps.py, homematicip/device.py, homematicip_demo/json_data/home.json, tests/test_devices.py
Hi,
this PR fixes HmIP-SWDM(-B2), that does not support SABOTAGE.
I also added a test and extended home.json.
Fixes #227 
BR
=> Fix HmIP-SWDM

CHANGELOG.md, homematicip/base/functionalChannels.py, homematicip/device.py, homematicip_demo/json_data/home.json, tests/test_devices.py
Hi,
this PR adds support for additional features.
Especially interesting these (hot) days: deviceOverheated
I added all features to the channel, and the more relevant(?) to the device.
Hope that fits.
BR
=> Add support for additional features

hmip_cli.py, homematicip/home.py
added Home.start_inclusion method
=> added --start-inclusion to hmip_cli.py

homematicip/device.py
This PR fixes the uses of the functional channel for the contact interface
=> Fix Contact Interface functional channel usage

CHANGELOG.md, homematicip/base/HomeMaticIPObject.py, homematicip/home.py, tests/aio_tests/notest_plugable_switch_measuring_async.py, tests/test_home.py
This is the base to allow adding and removing devices without restarting HA
=> Add create and remove event trigger

homematicip_demo/json_data/home.json
Add some device to home.json
- HmIP-BSM
- HmIP-FSM
- HmIP-PS
All devices are already created so no further action needed
=> Add some device to home.json

homematicip/aio/device.py
I missed to set the correct inheritance in the previous PR.
Sorry.
=> Fix wrong inheritance

homematicip_demo/json_data/home.json, tests/aio_tests/test_async_groups.py, tests/test_groups.py
I fixed some test data:
- Add heating profile names
- Fix IDs
This TD can be used with HA.
=> Fix Test data

homematicip/base/helpers.py, tests/test_hmip_cli.py
=> updated handle_config to replace all kind of sgtins

homematicip/home.py
Hi,
this PR improves the update of the Home object.
=> improve update of home

homematicip/aio/class_maps.py, homematicip/aio/device.py, homematicip/device.py, homematicip_demo/json_data/home.json, tests/aio_tests/test_async_device.py, tests/test_devices.py
Hi,
FSI16 was missing in class_maps for async.
I also manipulated some test data to support labels. I test labels in HA.
BR
=> Fix FSI16 & add some labels to test data

homematicip/aio/device.py, homematicip/device.py, homematicip_demo/json_data/home.json, tests/aio_tests/test_async_device.py, tests/test_devices.py
This simplifies also follow up code in HA
=> Switch param order for cover to simplify code

CHANGELOG.md, hmip_cli.py, homematicip/aio/home.py, homematicip/home.py, homematicip_demo/fake_cloud_server.py, tests/aio_tests/test_async_home.py, tests/test_home.py
=> added home.activate_absence_permanent

homematicip_samples/.gitignore, homematicip_samples/CheckPresenceOnPing/CheckPresenceOnPing.pyproj, homematicip_samples/CheckPresenceOnPing/Readme.md, homematicip_samples/CheckPresenceOnPing/requirements.txt, homematicip_samples/CheckPresenceOnPing/scan.py, homematicip_samples/ControlDevides/Readme.md, homematicip_samples/ControlDevides/switch_on_off.py, homematicip_samples/GetDevicesAndValues/README.md, homematicip_samples/GetDevicesAndValues/api.py, homematicip_samples/GetDevicesAndValues/api_with_url.py, homematicip_samples/LICENSE, homematicip_samples/QRCodeGenerator/QRCodeGenerator.pyproj, homematicip_samples/QRCodeGenerator/Readme.md, homematicip_samples/QRCodeGenerator/qrcodegenerator.py, homematicip_samples/QRCodeGenerator/qrcodes_template.html, homematicip_samples/QRCodeGenerator/requirements.txt, homematicip_samples/README.md, homematicip_samples/SampleLibrary.sln, homematicip_samples/SampleTemplate/Readme.md, homematicip_samples/SampleTemplate/SampleTemplate.pyproj, homematicip_samples/SampleTemplate/empty.py, homematicip_samples/SampleTemplate/requirements.txt, homematicip_samples/TelegramNotificationBot/Readme.md, homematicip_samples/TelegramNotificationBot/TelegramNotificationBot.py, homematicip_samples/TelegramNotificationBot/TelegramNotificationBot.pyproj, homematicip_samples/TelegramNotificationBot/requirements.txt
https://github.com/coreGreenberet/homematicip-samples.git has not seen any updates since 2019.
Include it in the main repository to have all in one place and so ease improvements in this area.
=> Include samples
